# Generated by Django 5.2.5 on 2025-10-01 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0005_auto_20200316_2250"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Movie_id", models.IntegerField()),
                ("Movie_name", models.CharField(max_length=100)),
                ("Movie_genre", models.CharField(max_length=100)),
                ("Movie_description", models.CharField(max_length=300)),
                (
                    "Release_year",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1900)]
                    ),
                ),
                (
                    "Movie_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
            ],
        ),
    ]
